#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if [ -f "package.json" ]; then
  yarn test && yarn lint-staged
fi

if [ $(git diff --cached --name-only src/validate.ts) ]; then
  yarn ts-node -P tsconfig.scripts.json  ./scripts/build*
  git add schema/tson.json
fi